name: Maven CI/CD

on:
  push:
    branches: [main, testing]
    
  pull_request:
    branches: [main, testing]

jobs:
 build_and_test:

  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21
    - name: Build project with Maven
      working-directory: roman-number
      run: mvn -B package --file pom.xml
    - name: Test and get report with JaCoCo
      working-directory: roman-number
      run: mvn clean test jacoco:report
    - name: Upload to coveralls with github actions
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: roman-number/target/site/jacoco/jacoco.xml
    - name: Check correct style
      run: mvn checkstyle:check
      working-directory: roman-number 